export const ADD_IMAGE_REQUEST_SUCCESS = 'ADD_IMAGE_REQUEST_SUCCESS'
export const ADD_IMAGE_REQUEST_ERROR = 'ADD_IMAGE_REQUEST_ERROR'
export const RESET_ADD_IMAGE_REQUEST = 'RESET_ADD_IMAGE_REQUEST'
export const UPDATE_ADD_IMAGE_REQUEST_STATUS = 'UPDATE_ADD_IMAGE_REQUEST_STATUS'