export const SET_CAPTURED_PHOTO_AND_LOADING = 'SET_CAPTURED_PHOTO_AND_LOADING'
export const CLEAR_CAPTURED_PHOTO = 'CLEAR_CAPTURED_PHOTO'
export const UPDATE_PHOTO_LOADED = 'UPDATE_PHOTO_LOADED'
export const UPDATE_PHOTO_CAPTURED_AND_LOADING = 'UPDATE_PHOTO_CAPTURED_AND_LOADING'