export const UPDATE_IMAGE_SEARCH_REQUEST_DATA =
  "UPDATE_IMAGE_SEARCH_REQUEST_DATA";
export const UPDATE_IMAGE_SEARCH_REQUEST_STATUS =
  "UPDATE_IMAGE_SEARCH_REQUEST_STATUS";
export const UPDATE_IMAGE_SEARCH_REQUEST_ERROR =
  "UPDATE_IMAGE_SEARCH_REQUEST_ERROR";
export const RESET_IMAGE_SEARCH = "CLEAR_IMAGE_SEARCH";
