export const UPDATE_INVNO_SEARCH_DATA = "UPDATE_INVNO_SEARCH_DATA";
export const UPDATE_INVNO_SEARCH_STATUS = "UPDATE_INVNO_SEARCH_STATUS";
export const RESET_INVNO_SEARCH = "RESET_INVNO_SEARCH";
export const SUBMIT_INVNO_SEARCH_FORM = "SUBMIT_INVNO_SEARCH_FORM";
export const UPDATE_ITEM_IMAGE_URL = "UPDATE_ITEM_IMAGE_URL";
export const UPDATE_SET_ITEM_CLICKED = "UPDATE_SET_ITEM_CLICKED";
