export const UPDATE_ITEM_ID_SEARCH_DATA = 'UPDATE_ITEM_ID_SEARCH_DATA'
export const UPDATE_ITEM_ID_SEARCH_STATUS = 'UPDATE_ITEM_ID_SEARCH_STATUS'
export const RESET_ITEM_ID_SEARCH = 'RESET_ITEM_ID_SEARCH'
export const SUBMIT_ITEM_ID_SEARCH_FORM = 'SUBMIT_ITEM_ID_SEARCH_FORM'